HISTCONTROL=ignoredups:ignorespace
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias vim='vim -p'
alias l='ls'
alias sl='ls'
alias yolo='rm -rf --no-preserve-root'
alias mkdir='mkdir -p'

alias desktopchanger='python ~/scripts/desktopChanger/client.py'
alias ai2_server='~/appengine-java-sdk-1.9.9/bin/dev_appserver.sh --port=8888 --address=0.0.0.0 appengine/build/war/'
alias ai2_build_server='cd ~/appinventor-sources/appinventor/buildserver && ant RunLocalBuildServer'
alias ai2_ant_all='cd ~/appinventor-sources/appinventor && ant && ant installplay && ai2_server'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias logcat='adb logcat -s '
alias ack='ack-grep --ackrc=/home/evan/.ackrc'
alias source-files='ack -f  --ignore-file=ext:swo --ignore-file=ext:swm --ignore-file=ext:swl --ignore-file=ext:swn --ignore-file=ext:swk'
alias sr='screen -X eval "chdir $PWD"'
alias q='make qemu-nox'
alias qg='make qemu-nox-gdb'



if [ -f ~/.git-completion.bash ]; then
    . ~/.git-completion.bash
fi

if [ -f ~/.name ]; then
  name=$(cat ~/.name)
else
  name=$(echo '')
fi

#Modifies the prompt
green=$(tput setaf 2)
reset=$(tput sgr0)

PS1='\[\033k\033\\\]\[$green\][$name\w]\$\[$reset\] ' #the \[\033k\033\\\] is some hack that screen uses to display the title

export JAVA_HOME="/usr/lib/jvm/java-7-oracle/"
export ANT_HOME="/usr/share/ant"
export QEMU="/home/evan/qemu-install/bin/qemu-system-i386"
# add my own scripts folder to path after everything else
PATH="/home/evan/.cabal/bin:${PATH}:/home/evan/scripts:~/Desktop/playground/Gshit/desktopchanger.py:${ANT_HOME}/bin:${JAVA_HOME}"
export PATH
export GOPATH="$HOME/Desktop/classes/824/code"

#adds mark jump command to terminal
source ~/.marksrc
